### ISSUE TITLE
关于字形

### ISSUE THREAD

**Issue by AmeroHan** [MY1L/unMing#3]
项目的glyph中只有两个字形，otf文件中的其他的字形是需要重绘吗？

**Comment by MY1L** [comment]
差不多是。glyph中是我觉得没问题的，其他的字形没有经过细致的描绘，比如笔画相交部分粘连。“慧及全球”是瞎画的。

不过现在特别需要拆偏旁组字清单（用现有偏旁可以组哪些字的列表）
和整理饼维基字符集（需要做哪些字符才能显示饼维基“不明”这一页所有字，是第一个目标；其次要显示特殊饼人名譬如“ʯnɯɯəɹ”“ｽｽ爻之〆X∠X∠”等）
